### ISSUE TITLE
Bug: Next page xpath is obsolute

### ISSUE THREAD

**Issue by sauravhiremath** [DiogoDantas/SoFIFA#2]
The **next button xpath** is currently
```
    .//a[@class="pjax btn"]/@href
```
for
```
    sofifa_parser/spiders/players_url.py
```

This link for next page does not work for [https://sofifa.com/players?offset=0](https://sofifa.com/players?offset=0) <br>
_as of 21st April, 2020_.

**Comment by sauravhiremath** [comment]
I will work on the fix @arnaldog12

**Comment by arnaldog12** [comment]
Thanks for this @sauravhiremath. 
I asked for review from @DiogoDantas. He may approve it!
